### ISSUE TITLE
[!] Unknown jailbreak. Aborting. with Electra

### ISSUE THREAD

**Issue by devAlikhani** [BishopFox/bfinject#19]
with tweaks disabled electra, i get "[!] Unknown jailbreak. Aborting." could someone help?

**Comment by riley-williams** [comment]
Having the same issue.
iPhone 7, 11.1.2, freshly jailbroken w/ Electra 1.0.3

bfinject is looking for /bootstrap/inject_criticald, which doesn't exist. /bootstrap doesn't exist either. I don't know what it looked like before or if I'm missing something, but it kinda looks like /electra contains what might've been in /bootstrap

Sooo, by recklessly replacing /bootstrap in bfinject with /electra:

# bash bfinject -p 392 -L decrypt 
[+] Electra detected.
cp: cannot create regular file '/electra/usr/local/bin/': No such file or directory
chmod: cannot access '/electra/usr/local/bin/jtool.liberios': No such file or directory
cp: cannot create regular file '/electra/usr/local/bin/': No such file or directory
bfinject: line 163: md5: command not found
bfinject: line 164: md5: command not found
cp: cannot stat '/electra/usr/local/bin/bfinject4realz': No such file or directory
chmod: cannot access '/electra/usr/local/bin/': No such file or directory
bfinject: line 175: tail: command not found
bfinject: line 175: cut: command not found
[+] Injecting into ''
[+] Getting Team ID from target application...
bfinject: line 190: tail: command not found
bfinject: line 190: cut: command not found
bfinject: line 190: cut: command not found
[+] WARNING: No Team ID found. Continuing regardless, but expect weird stuff to happen.
[+] Thinning dylib into non-fat arm64 image
[!] WARNING: Wasn't able to thin the dylib.
[+] Signing injectable .dylib with Team ID  and platform entitlements...
jtool dylib signing error. barfing.


Manually creating /electra/usr/local/bin quiets cp and chmod, but I still don't have cut or tail...

**Comment by riley-williams** [comment]
I'm using iPhone 7, iOS 11.1.2, Electra 1.0.3 (never jailbroken with a previous version)
This fix only addresses the issues with this version of Electra, and will break bfinject for other versions of Electra/LiberiOS without extra logic to properly detect them.

## Fixed by doing the following:
- Make sure Core Utilities is installed. It provides `md5sum`, `tail`, and maybe something else...

### In bfinject:
- Change `md5` to `md5sum` on lines 163 and 164. (this probably also fixes #15)

**Under** `# Be a good netizen and tidy up your litter`
- Change the file paths from `/bootstrap/usr/local/bin/...` to `/usr/local/bin/...`

**Under** `# Detect LiberiOS vs Electra`
- Change the if from `/bootstrap/inject_criticald` to `/electra/inject_criticald`
- Change the file paths from `/bootstrap/usr/local/bin/...` to `/usr/local/bin/...`

### From a root shell:
- Run: `mkdir /usr/local/bin` to create the `bin` folder if it doesn't already exist.

**Comment by devAlikhani** [comment]
@riley-williams thanks, fixed with your solution
