### ISSUE TITLE
'test' and 'decrypt' don't seem to work if a modal view is open

### ISSUE THREAD

**Issue by flockoffiles** [BishopFox/bfinject#9]
I tried using 'test' and 'decrypt' features with an app which displayed a modal view when launched.
In that case, although the library injection did succeed, no UI from 'test' or 'decrypt' was shown.

I wonder if something could be done about it?

**Comment by 0xhaggis** [comment]
I'm now checking for `topmostPresentedViewController` on the app's `keyWindow`, and using it instead of `rootViewController` when displaying `UIAlertController`s. It seems to work now (I tested it with the WordPress Swift app, which exhibited the behavior you describe).

Please try again, let me know if that's fixed it for you.

**Comment by 0xhaggis** [comment]
Fixed as far as I can tell. Closing.
